# docker-compose.yml
version: "3.8"
services:
  web:
    build:
      context: ./server
      dockerfile: dockerfile
    image: web_server:latest
    container_name: web_server-container
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  webphp:
    build:
      context: ./serverphp
      dockerfile: dockerfile
    image: web_server_php:latest
    container_name: web_server_php-container
    # ports:
    #   - "8081:8081"
    volumes:
      - ./serverphp:/var/www/html
    restart: always

  db:
    image: mariadb:latest
    container_name: mariadb_container
    volumes:
      - ./mariadb/data/:/var/lib/mysql
      - ./mariadb/init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: exampledb
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: web_server_nginx:latest
    container_name: web_server_nginx-container
    ports:
      - "80:80"
    depends_on:
      - web
      - webphp
