version: "3"
services:
  student_rpc:
    container_name: student_rpc
    build:
      context: ./app
      dockerfile: dockerfile.dev
    environment:
      - DB_URI=mongodb://mongo:27017/devops_db
      - NODE_ENV=dev
    networks:
      - microservice_network
    depends_on:
      - mongo
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - microservice_network

networks:
  microservice_network:
    name: microservice_network
    external: true

volumes:
  mongodb_data_container:
  node_modules:
