# Specify the base image
FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Replace it with our custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/