# ใช้ Nginx ในเวอร์ชัน alpine base image
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# คัดลอกไฟล์การตั้งค่า Nginx ไปยังที่ทำงานของ Nginx
COPY nginx.conf /etc/nginx/nginx.conf
