# Node.js Dockerfile
FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=dev

# ติดตั้ง nodemon
RUN npm install -g nodemon

COPY . .

EXPOSE 8000

CMD ["npm", "run", "dev"]