version: "3"
services:
  register:
    container_name: register_gateway
    build:
      context: ./app
      dockerfile: dockerfile.dev
    environment:
      - NODE_ENV=dev
    restart: always
    ports:
      - "7001:8000"
    networks:
      - microservice_network
      - default
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

  nginx:
    container_name: register_nginx
    build: nginx/
    ports:
      - "80:80"
    depends_on:
      - register
    networks:
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    name: microservice_network
    external: true
  microservice_network:
    name: microservice_network
    external: true

volumes:
  node_modules:
